---
-
 
  # Target: where our play will run and options it will run with
  hosts: 192.168.1.150
  # Task: the list of tasks that will be executed within the playbook
  tasks:
- name: Disable Domain firewall
  win_firewall:
    state: disabled
    profiles:
    - Private
    - Public
  tags: disable_firewall
...
